# Rust formatter configuration
# See: https://rust-lang.github.io/rustfmt/

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Function formatting
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Comment formatting
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
comment_width = 100

# String formatting
format_strings = true
format_macro_matchers = true

# Trailing elements
trailing_comma = "Vertical"
trailing_semicolon = true

# Space formatting
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Misc
merge_derives = true
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true

# Unstable features (nightly only)
# Uncomment if using nightly compiler
# unstable_features = true
# format_macro_bodies = true
# imports_layout = "HorizontalVertical"